version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Radical.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/Radical"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/targets"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
