#
#     DEVELOPMENT BRANCH
#
# build in Debug mode and deploy to MyGet.org as pre-release

- branches:
    only:
    - develop

  configuration: Debug
  platform: Any CPU

  environment:
    use_build_number_in_packages: true

  artifacts:
    - path: src\build\Debug
    - path: src\build\nuget\*.nupkg

  cache:
    - src\packages -> src\**\packages.config

  before_build:
    - nuget restore "src\Radical.sln"

  build:
    project: src\Radical.sln
    verbosity: minimal

  after_build:
    - md "src\build\nuget"
    - nuget pack "src\nuget\Radical.nuspec" -Version "%GitVersion_NuGetVersion%" -Properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"

  pull_requests:
    do_not_increment_build_number: true

  test:
    categories:
      except:
      - ObjectDumper
      - AsyncWorker

  deploy:
  - provider: Environment
    name: MyGet feed
    on:
      branch: develop

#
#   MASTER BRANCH
#
# build in Release mode and deploy to NuGet.org
- branches:
    only:
    - master

  configuration: Release
  platform: Any CPU

  environment:
    use_build_number_in_packages: true

  artifacts:
    - path: src\build\Release
    - path: src\build\nuget\*.nupkg

  cache:
    - src\packages -> src\**\packages.config

  before_build:
    - nuget restore "src\Radical.sln"

  build:
    project: src\Radical.sln
    verbosity: minimal

  after_build:
    - md "src\build\nuget"
    - nuget pack "src\nuget\Radical.nuspec" -Version "%GitVersion_NuGetVersion%" -Properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"

  pull_requests:
    do_not_increment_build_number: true

  test:
    categories:
      except:
      - ObjectDumper
      - AsyncWorker

  deploy:
  - provider: Environment
    name: NuGet public feed
    on:
      branch: master