image: Visual Studio 2017
skip_branch_with_pr: true
skip_tags: true
pull_requests:
  do_not_increment_build_number: true

test:
  categories:
    except:
      - ObjectDumper
      - AsyncWorker

for:

-
  branches:
    only:
      - develop

  build_script:
    - cmd: Build.cmd
  
  artifacts:
    - path: build\Debug
    - path: nugets\*.nupkg

  deploy:
    - provider: Environment
      name: MyGet feed
      artifact: /.*\.nupkg/
-
  branches:
    only:
      - master

  build_script:
    - cmd: Build.cmd release

  artifacts:
    - path: build\Release
    - path: nugets\*.nupkg

  deploy:
    - provider: Environment
      name: NuGet public feed
      artifact: /.*\.nupkg/

    - provider: GitHub    
      release: $(GitVersion_NuGetVersion)
      description: 'Release v$(GitVersion_NuGetVersion)'
      auth_token:
        secure: 2ijF4OfPYfIUTunubL/Z04ogADL9sx/gKW1jMRNJnAa1OpHZpSvCKmP0gvNs8C7h
      artifact: /.*\.nupkg/, build\Release.zip
