on:
  push:
    branches:
    - master
    - release-*
    - '!release-1.6'
    tags:
    - '*.*.*'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    env:
      GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and Test on ${{ matrix.runs-on }}
        if: contains(matrix.runs-on, 'windows')
        run: ./build.cmd
      
      - name: Build and Test on ${{ matrix.runs-on }}
        if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
        run: ./build.sh
    
      - name: Push to MyGet (on Windows)
        if: contains(matrix.runs-on, 'windows')
        run: dotnet nuget push src\Radical\Bin\Release\*.nupkg --skip-duplicate --source https://www.myget.org/F/radical-unstable/api/v2/package --api-key ${{ secrets.MyGet_API_Key }}
