on:
  push:
    branches:
    - master
    - release-*
    - '!release-1.6'
    tags:
    - '*.*.*'
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - run: dotnet --info
    - uses: actions/checkout@v2.0.0
    - if: contains(matrix.runs-on, 'windows')
      run: ./build.cmd
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
